### ISSUE TITLE
Switch type number

### ISSUE THREAD

**Issue by HubSteven** [lhm0/rotating_display_color#1]
What is the type of switch you used on the power supply board for SW1A? It's not listed in the bom.

**Comment by lhm0** [comment]
I bought this switch in Germany:

https://www.reichelt.de/schiebeschalter-90-rm5-08-1x-ein-ein-ss-25536-n-p105721.html?&nbc=1#

There is a data sheet on their page.

The manufacturer is APEM, type SS 25536 N

The component is also available on mouser.com .

**Comment by HubSteven** [comment]
Thank you!
